server:
  port: 8090
  compression:
    enabled: true
    mime-types: text/html,application/json
    min-response-size: 3KB
  servlet:
    context-path: /api

spring:
  application:
    name: tour-generator

  ai:
    openai:
      api-key: ${GEMINI_API_KEY}
      base-url: https://generativelanguage.googleapis.com
      chat:
        completions-path: /v1beta/openai/chat/completions
        options:
          model: gemini-2.5-flash-lite # gemini-2.5-flash
          temperature: 0.8


  datasource:
    url: jdbc:mysql://localhost:3308/tour-generator?ssl-mode=REQUIRED
    username: root
    password: Password123!
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      dialect: org.hibernate.dialect.MySQLDialect
      hibernate:
        format_sql: true
    show-sql: true
    open-in-view: false
    # da settare a true se sql.init.mode: always
    defer-datasource-initialization: true
  data:
    jpa:
      repositories:
        bootstrap-mode: DEFAULT
  sql:
    init:
      mode: NEVER # esegue le istruzioni presenti in resources/data.sql ad ogni avvio di applicazione



# LOGGING
logging:
  level:
    org:
      springframework:
        boot: info
        security: info
      hibernate:
        orm:
          connections:
            pooling: off
          jdbc:
            bind: trace

